scenario_parameters:
  time_step: 60
  MJD_start: 59348.5
  MJD_end: 59349.0
  max_time_step: 60
  output_directory: out/
initial_orbtial_parameters:
  dim_state: 6
  initial_state:
  - 4581588.124900462
  - 5156063.561654096
  - 3459956.0545526473
  - -4343.528556858466
  - 12.951702141652406
  - 5776.937306589448
  initial_state_type: ECI
propagator_truth_settings:
  earth_gravity_model_order: 100
  earth_gravity_model_degree: 100
  third_body_attraction: true
  third_body_sun: true
  third_body_moon: true
  solid_earth_tide: true
  ocean_tide_loading: true
  solar_radiation_pressure: true
  atmospheric_drag: false
  relativity_effect: true
  srpCoef: 1.23
  srpArea: 8.73
  dragCoef: 2.0
  dragArea: 4.091655
  satMass: 961.831
supporting_files:
  gravity_file: ./auxdata/GGM03S.txt
  ephemeris_file: ./auxdata/linux_p1550p2650.440
  ERP_file: ./auxdata/cod21587.erp
